### ISSUE TITLE
Provisioning is currently disabled due to a maintenance break?

### ISSUE THREAD

**Issue by mtnrunr** [SharePoint/sp-dev-provisioning-templates#58] opened 2022-01-05 18:09 UTC
Any ETA on when Provisioning will be available for Learning Pathways?  Getting:  

Provisioning is currently disabled due to a maintenance break.

We expect the service to be online again in January 2022.

**Comment by TracyGH** [comment] 2022-01-07 15:41
Ditto!

**Comment by Matt-Thomp** [comment] 2022-01-07 15:44
Does anyone managing it, have rough idea when it will be back online??

**Comment by BlakeSweeting** [comment] 2022-01-08 11:59
I'd also like to know when it will be back online

**Comment by BlakeSweeting** [comment] 2022-01-16 08:15
Any update?

**Comment by TracyGH** [comment] 2022-01-19 16:28
Please provide more specific instruction/guidance around how to 'provision the templates manually'. 

![image](https://user-images.githubusercontent.com/38665906/150172899-bd221144-46f0-43c7-8c86-edbdb9d99506.png)

**Comment by BlakeSweeting** [comment] 2022-01-19 20:07
> Please provide more specific instruction/guidance around how to 'provision the templates manually'.
> 
> ![image](https://user-images.githubusercontent.com/38665906/150172899-bd221144-46f0-43c7-8c86-edbdb9d99506.png)

Id also be interested in a guide for manually provisioning the templates.

**Comment by TracyGH** [comment] 2022-01-24 02:58
Hi @VesaJuvonen! Do you have any insight into when the provisioning template will be back online? 

I tried following the [manual deployment instructions](https://docs.microsoft.com/en-us/office365/customlearning/custom_manualsetup), but there's a bunch of content missing compared to the auto-provision version.

**Comment by Matt-Thomp** [comment] 2022-01-24 13:39
This is the problem when Microsoft sub-contract out a solution and not being in control of it. and the work is passed on to third parties and this creates this problem.  Starting to see it more with Microsoft where some solutions are being farmed out to third parties.  Maybe to help reduce costs etc.  This process needs to be managed properly, either Microsoft take back full ownership of the solution or the people maintaining it need to have a proper maintenance calendar/schedule so user can plan work around it.

**Comment by TomPetra** [comment] 2022-01-27 15:35
After opening a support case request with Microsoft here is what they said
+++++++++++
As per the message issue might get resolved by end of January. Please refer open source platform like github for more information.
Reference article:- https://lookbook.microsoft.com/service-description
https://github.com/SharePoint/sp-dev-provisioning-templates/issues/58
Please refer to the following documentation about provisioning using PnP:
https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/introducing-the-pnp-provisioning-engine
https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-remote-provisioning

I wrote back to them asking for:
1. a firm date
2. comments on the issue of missing content reported above
3. If I do the manual process and the site comes back on Jan 31, will they support me re-install using the auto-provision online method to fix any missing content.

I will post their update as soon as they respond.

Cheers

**Comment by TP4312** [comment] 2022-01-27 21:40
Microsoft support response is evasive:

"I do apologize for the inconvenience caused but LookBook is a open source platform and not supported by Microsoft. Also we do not support scripting and GitHub solutions. I could have helped on best efforts if there was any issue while provisioning template, but as the issue is worldwide we need to wait for further update on LookBook website or GitHub"

So I guess we just have to wait until the end of the month :(

**Comment by AltonPM** [comment] 2022-02-01 18:33
It's back :-)

**Comment by BlakeSweeting** [comment] 2022-02-01 18:36
When provisioning any of the templates, I get "Unfortunately your site provisioning at least partially failed". A few people have also got this issue.

**Comment by AnthonyPretorius** [comment] 2022-02-02 04:55
> When provisioning any of the templates, I get "Unfortunately your site provisioning at least partially failed". A few people have also got this issue.

Yeah, same here

**Comment by VesaJuvonen** [comment] 2022-02-07 21:09
Just to follow up on this. We had a still random issues on early last week on the service, but these should be now all resolved. If you encounter any issues, please do submit a NEW issue (per case) and include the mentioned correlation ID as that provides us away to see the issue from logs. Thx.

Closing this for now as the primary topic - maintenance break - as been resolved.

**Closed by VesaJuvonen** 2022-02-07 21:09 UTC
